# the level is an array of strings that each
# represent a row of 'blocks' that the level is
# built up of.
# "O" = normal block
# "X" = finish block (quits level)

LEVEL_TEMPLATE_NOT_USED = [
"OOOOOOOOOOOOOOOOOOOOOOOOO",
"O                       O",
"O                       O",
"O                       O",
"O                       O",
"O                       O",
"O                       O",
"O                       O",
"O                       O",
"O                       O",
"O                       O",
"O                       O",
"O                       O",
"O                       O",
"O                       O",
"O                       O",
"O                       O",
"O                       O",
"O                       O",
"O                      XO",
"OOOOOOOOOOOOOOOOOOOOOOOOO"]
level = [
"OOOOOOOOOOOOOOOOOOOOOOOOO",
"O                       O",
"O                       O",
"O                       O",
"O                       O",
"O                       O",
"O                       O",
"O                       O",
"O                       O",
"O                       O",
"O                       O",
"O                       O",
"O                       O",
"O                       O",
"O                       O",
"O                       O",
"O                       O",
"O                     O O",
"O                    OO O",
"O                   OOOXO",
"OOOOOOOOOOOOOOOOOOOOOOOOO"]
level2 = [
"OOOOOOOOOOOOOOOOOOOOOOOOO",
"O                       O",
"O                       O",
"O                       O",
"O                       O",
"O                       O",
"O                       O",
"O                       O",
"O                       O",
"O                       O",
"O                       O",
"O                       O",
"O                       O",
"O                       O",
"O                       O",
"O                       O",
"O         X             O",
"O        OO             O",
"O       OO              O",
"O      OO               O",
"OOOOOOOOOOOOOOOOOOOOOOOOO"]
level3 = [
"OOOOOOOOOOOOOOOOOOOOOOOOO",
"O                       O",
"O                       O",
"OO                      O",
"O O                     O",
"O  O                    O",
"O   O                   O",
"O                       O",
"O                       O",
"O                       O",
"O                       O",
"O                       O",
"O                       O",
"O                       O",
"O                       O",
"O                       O",
"O                       O",
"O                       O",
"O             OOOOOOOOO O",
"O             OX        O",
"OOOOOOOOOOOOOOOOOOOOOOOOO"]
level4 = [
"OOOOOOOOOOOOOOOOOOOOOOOOO",
"O                       O",
"O                       O",
"O                       O",
"O                       O",
"O                       O",
"O                       O",
"O                       O",
"O                       O",
"O                       O",
"O          X            O",
"O                       O",
"O                       O",
"O             O         O",
"O                       O",
"O                       O",
"O         O             O",
"O                       O",
"O                       O",
"O             O         O",
"OOOOOOOOOOOOOOOOOOOOOOOOO"]
level5 = [
"OOOOOOOOOOOOOOOOOOOOOOOOO",
"O  O                    O",
"O  O   O     O          O",
"O  O      O             O",
"O  O                    O",
"O  O   O     O          O",
"O  O    OOOOO           O",
"O  O                    O",
"O  O         OOOOOOOOOOOO",
"O  O         O          O",
"O  O         O    OO    O",
"O  OOOOOOOOOOO     O    O",
"O  O         OO    O    O",
"O  O         O     O    O",
"O  O     OO  O     O    O",
"O  O    OO   O    OO    O",
"O  O     O   O     O    O",
"O        O   O   OOO    O",
"O    OO  O  OO  OOOO    O",
"O   OOOO O     OOOOOOOOXO",
"OOOOOOOOOOOOOOOOOOOOOOOOO"]
level6 = [
"OOOOOOOOOOOOOOOOOOOOOOOOO",
"O O                    XO",
"O O                     O",
"O OO OOOOOOOOOOOOOOOOO  O",
"O O  O                  O",
"O O OO                  O",
"O O  O                  O",
"O O  O                  O",
"O OO O                  O",
"O O  O                  O",
"O O  O                  O",
"O O OO                  O",
"O O  O                  O",
"O O  O                  O",
"O OO O                  O",
"O O  O                  O",
"O O  O                  O",
"O   OO                  O",
"O    O                  O",
"O    O                  O",
"OOOOOOOOOOOOOOOOOOOOOOOOO"]
level7 = [
"OOOOOOOOOOOOOOOOOOOOOOOOO",
"O                       O",
"O                       O",
"O                       O",
"O                       O",
"O                       O",
"O                       O",
"O                       O",
"O                       O",
"O                       O",
"O                       O",
"O                       O",
"OOOOOOOOOOOOOOOOX       O",
"O                       O",
"O                       O",
"O                       O",
"O                       O",
"O                       O",
"O                       O",
"O                       O",
"OOOOOOOOOOOOOOOOOOOOOOOOO"]