# the level is an array of strings that each
# reOresent a row of 'blocks' that the level is
# built uO of.
# "O" = normal block
# "F" = finish block (quits level)
# "X" = sOike block
# "J" = jumO block

level1 = [
"OOOOOOOOOOOOOOOOOOOOOOOOO",
"O                       O",
"O                       O",
"O                       O",
"O                       O",
"O                       O",
"O                       O",
"O                       O",
"O                       O",
"O                       O",
"O                       O",
"O                       O",
"O                       O",
"O                       O",
"O                       O",
"O                       O",
"O                       O",
"O                       O",
"O                       O",
"O                      FO",
"OOOOOOOOOOOOOOOOOOOOOOOOO"]
level2 = [
"OOOOOOOOOOOOOOOOOOOOOOOOO",
"O                       O",
"O                       O",
"O                       O",
"O                       O",
"O                       O",
"O                       O",
"O                       O",
"O                       O",
"O                       O",
"O                       O",
"O                       O",
"O                       O",
"O                       O",
"O                       O",
"O                       O",
"O                       O",
"O                 OOO   O",
"O                 O     O",
"O                 OF    O",
"OOOOOOOOOOOOOOOOOOOOOOOOO"]
level3 = [
"OOOOOOOOOOOOOOOOOOOOOOOOO",
"O                       O",
"O                       O",
"O                       O",
"O                       O",
"O                       O",
"O                       O",
"O                       O",
"O                       O",
"O                       O",
"O                       O",
"O                       O",
"O                       O",
"O                       O",
"O           OOOOO       O",
"O               O       O",
"O               O       O",
"O           OX  O       O",
"O          OO   O       O",
"O         OO F  O       O",
"OOOOOOOOOOOOOOOOOOOOOOOOO"]
level4 = [
"OOOOOOOOOOOOOOOOOOOOOOOOO",
"O             O         O",
"O             O         O",
"O             OF        O",
"O             OOOOO     O",
"O                       O",
"O                       O",
"O                       O",
"O                       O",
"O                       O",
"O                       O",
"O                       O",
"O                       O",
"O                       O",
"O                       O",
"O                       O",
"O                       O",
"O                       O",
"O                       O",
"O                    JJJO",
"OOOOOOOOOOOOOOOOOOOOOOOOO"]
level5 = [
"OOOOOOOOOOOOOOOOOOOOOOOOO",
"O           O           O",
"O           O           O",
"O           O           O",
"O           OF  X       O",
"O           O   OOO     O",
"O           OOOOOOOO    O",
"O               OOOOO   O",
"O                       O",
"O                       O",
"O                       O",
"O                       O",
"O                       O",
"O                       O",
"O                       O",
"O                       O",
"O                       O",
"O                    JJJO",
"O                       O",
"OXXXXX                  O",
"OOOOOOOOOOOOOOOOOOOOOOOOO"]
level6 = [
"OOOOOOOOOOOOOOOOOOOOOOOOO",
"O                       O",
"O  OOOOOO               O",
"O  O     O    O         O",
"O  O      O   O         O",
"O  O       O  O         O",
"O  O         OO    OOOOOO",
"O  O        O O         O",
"O  O       O  O         O",
"O  O      O   OOOOOO    O",
"O  O     O    OO        O",
"O  O OO       OOO      OO",
"O  OOOOO      OOOO    OOO",
"O       O     OOOOO  OOOO",
"O        OO   O         O",
"O            OO         O",
"O          OO O         O",
"O       OO    O         O",
"O      OOOO   O         O",
"O     OOOOOOOOOF   XX   O",
"OJJOOOOOOOOOOOOOOOOOOOOOO"]
level7 = [
"OOOOOOOOOOOOOOOOOOOOOOOOO",
"O O                     O",
"O O                     O",
"O                       O",
"O O                     O",
"O O                     O",
"O O                     O",
"O O                     O",
"O O                     O",
"O O                     O",
"O O                     O",
"O O                     O",
"O O                     O",
"O O                     O",
"O O                     O",
"O OOOOOOO               O",
"O       OO              O",
"O       O O             O",
"O       O  O            O",
"O       O   O          FO",
"OJOOOOOOOOOOOOOOOOOOOOOOO"]